import '@styles/index.scss';
import '@styles/global.scss';

import { contentFont } from '@constants/fonts';
import type { Metadata } from 'next';

import MyLayout from '@/layouts';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayout {
  children: React.ReactElement;
}

export default function RootLayout({ children }: IRootLayout) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          contentFont.className,
        )}
      >
        <MyLayout>{children}</MyLayout>
      </body>
    </html>
  );
}
